(() => {
  const $=id=>document.getElementById(id);
  const baseE={1:1700,2:2150,3:2500,4:3200,5:3900,6:4600},baseG={1:6200,2:7800,3:9500,4:12200,5:15000,6:17800};
  const prop={flat:.78,terrace:.92,semi:1,detached:1.18,bungalow:1.08},eff={efficient:.82,average:1,inefficient:1.22},occ={low:.94,mixed:1,high:1.1};
  let calculated=false,last={e:0,g:0,mode:'estimate'},comparison=null;
  const fmt=n=>Math.round(n).toLocaleString('en-GB')+' kWh';
  const actualFields=()=>document.querySelectorAll('.actual-only').forEach(el=>el.style.display=$('calcMode').value==='actual'?'block':'none');
  $('calcMode').addEventListener('change',actualFields);

  function stateFromCurrent(){return{property:$('calcProperty').value,bedrooms:+$('calcBedrooms').value,occupants:+$('calcOccupants').value,heating:$('calcHeating').value,efficiency:$('calcEfficiency').value,daytime:$('calcDaytime').value,ev:$('calcEv').value,solar:$('calcSolar').value};}
  function estimate(s){const b=+s.bedrooms,p=+s.occupants;let e=baseE[b]||5200;e+=Math.max(0,p-b)*320;e*=prop[s.property]||1;e*=occ[s.daytime]||1;if(s.ev==='yes')e+=2200;if(s.solar==='yes')e*=.78;if(s.heating==='electric')e+=6500;if(s.heating==='heatpump')e+=2800;let g=0;if(s.heating==='gas'){g=(baseG[b]||20000)+Math.max(0,p-b)*400;g*=prop[s.property]||1;g*=eff[s.efficiency]||1;g=Math.max(3000,g);}return{e:Math.max(1000,e),g};}
  function band(value,base,label,marker){if(!value||!base)return;const ratio=value/base;label.textContent=ratio<.8?'Lower than tool baseline':ratio<=1.2?'Within tool range':'Higher than tool baseline';marker.style.left=Math.max(3,Math.min(97,((ratio-.4)/1.4)*100))+'%';}
  function warnActual(e,g){const warnings=[];if(e&&(e<500||e>30000))warnings.push('Electricity is outside the broad range used by this tool.');if(g&&(g<1000||g>60000))warnings.push('Gas is outside the broad range used by this tool.');return warnings;}

  function calculate(scroll=true){const current=stateFromCurrent(),est=estimate(current),mode=$('calcMode').value;let e=est.e,g=est.g;if(mode==='actual'){const ae=+$('calcElectric').value,ag=+$('calcGas').value;if(!ae&&!ag){$('calcWarning').textContent='Enter at least one annual kWh figure, or choose an estimate.';$('calcWarning').classList.add('show');return false;}const warnings=warnActual(ae,ag);$('calcWarning').textContent=warnings.join(' ');$('calcWarning').classList.toggle('show',warnings.length>0);e=ae||e;g=current.heating==='gas'?(ag||g):0;}else $('calcWarning').classList.remove('show');last={e,g,mode,current,currentEstimate:est};$('electricResult').textContent=fmt(e);$('gasResult').textContent=g?fmt(g):'Not applicable';const base=estimate({...current,solar:'no'});band(e,base.e,$('electricBand'),$('electricMarker'));$('gasRangeRow').hidden=!g;if(g)band(g,base.g,$('gasBand'),$('gasMarker'));$('rangeCard').hidden=false;const data=[['Property',$('calcProperty').selectedOptions[0].text],['Bedrooms',$('calcBedrooms').value],['Occupants',$('calcOccupants').value],['Heating',$('calcHeating').selectedOptions[0].text],['EV',$('calcEv').value==='yes'?'Yes':'No'],['Solar',$('calcSolar').value==='yes'?'Yes':'No']];$('calcSummary').innerHTML=data.map(([k,v])=>`<div class="summary-item"><span>${k}</span><strong>${v}</strong></div>`).join('');$('calcNote').textContent=mode==='actual'?'Actual annual kWh anchors the current result. Future scenarios use modelled differences, so they remain indicative.':'Indicative estimate based on the household scenario. Actual annual kWh is more reliable.';calculated=true;if(scroll)$('calcResults').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});window.trackSafe?.('calculator_completed',{mode});return true;}

  function comparisonState(){const current=last.current;return{...current,heating:$('scenarioHeating').value==='same'?current.heating:$('scenarioHeating').value,occupants:$('scenarioOccupants').value==='same'?current.occupants:+$('scenarioOccupants').value,daytime:$('scenarioDaytime').value==='same'?current.daytime:$('scenarioDaytime').value,ev:$('scenarioEv').value==='same'?current.ev:$('scenarioEv').value,solar:$('scenarioSolar').value==='same'?current.solar:$('scenarioSolar').value,efficiency:$('scenarioEfficiency').value==='same'?current.efficiency:$('scenarioEfficiency').value};}
  function deltaText(delta){const sign=delta>0?'+':'';return `${sign}${Math.round(delta).toLocaleString('en-GB')} kWh`;}
  function compare(){if(!calculated&&!calculate(false))return;const scenario=comparisonState(),scenarioEstimate=estimate(scenario);let e=scenarioEstimate.e,g=scenarioEstimate.g;let anchored=false;if(last.mode==='actual'){e=Math.max(0,last.e+(scenarioEstimate.e-last.currentEstimate.e));if(scenario.heating==='gas')g=Math.max(0,last.g+(scenarioEstimate.g-last.currentEstimate.g));else g=0;anchored=true;}comparison={name:$('scenarioName').value.trim()||'Future household',state:scenario,e,g,anchored};const de=e-last.e,dg=g-last.g;const direction=(d)=>d>0?'higher':d<0?'lower':'unchanged';$('scenarioResults').hidden=false;$('scenarioResults').innerHTML=`<div class="scenario-head"><div><span>COMPARISON</span><h3>${comparison.name}</h3></div><span class="scenario-confidence">${anchored?'Actual-anchored model':'Estimated model'}</span></div><div class="scenario-deltas"><article><span>Electricity difference</span><strong class="${direction(de)}">${deltaText(de)}</strong><small>${direction(de)} than current</small></article><article><span>Gas difference</span><strong class="${direction(dg)}">${deltaText(dg)}</strong><small>${direction(dg)} than current</small></article></div><p>${anchored?'The current actual result is adjusted by the modelled difference between household scenarios.':'Both current and comparison results use the same indicative model.'}</p><div class="helper-actions no-print"><button class="btn btn-light" type="button" id="saveComparison">Save comparison to Command Centre</button><button class="btn btn-light" type="button" id="printComparison">Print comparison</button></div>`;document.getElementById('saveComparison').onclick=saveComparison;document.getElementById('printComparison').onclick=()=>window.print();window.trackSafe?.('scenario_compared');}
  function saveComparison(){if(!comparison)return;let state={};try{state=JSON.parse(localStorage.getItem('saveEarnPaulV31Plan'))||{};}catch(_){};Object.assign(state,{version:'3.1',propertyType:$('calcProperty').value,bedrooms:$('calcBedrooms').value,occupants:$('calcOccupants').value,heating:$('calcHeating').value,efficiency:$('calcEfficiency').value,daytime:$('calcDaytime').value,ev:$('calcEv').value,solar:$('calcSolar').value,energyMode:'actual',actualElectric:String(Math.round(last.e)),actualGas:String(Math.round(last.g))});state.meta={...(state.meta||{}),scenarioComparison:{name:comparison.name,e:Math.round(comparison.e),g:Math.round(comparison.g),currentE:Math.round(last.e),currentG:Math.round(last.g),savedAt:new Date().toISOString()},updatedAt:new Date().toISOString()};localStorage.setItem('saveEarnPaulV31Plan',JSON.stringify(state));window.showToast?.('Comparison saved to Command Centre');window.trackSafe?.('scenario_saved');}

  $('calculateEnergy').onclick=()=>calculate();$('calculatorForm').addEventListener('change',()=>{if(calculated)calculate(false)});$('calculatorForm').addEventListener('input',()=>{if(calculated)calculate(false)});$('compareScenario').onclick=compare;document.querySelectorAll('#scenarioPanel select,#scenarioPanel input').forEach(el=>el.addEventListener('change',()=>{if(calculated&&!$('scenarioResults').hidden)compare();}));$('resetScenario').onclick=()=>{$('scenarioName').value='Future household';['scenarioHeating','scenarioOccupants','scenarioDaytime','scenarioEv','scenarioSolar','scenarioEfficiency'].forEach(id=>$(id).value='same');$('scenarioResults').hidden=true;comparison=null;};
  $('resetEnergy').onclick=()=>{$('calculatorForm').reset();actualFields();calculated=false;comparison=null;$('electricResult').textContent='—';$('gasResult').textContent='—';$('rangeCard').hidden=true;$('calcSummary').innerHTML='';$('scenarioResults').hidden=true;$('calcNote').textContent='Complete the details and calculate. Actual annual kWh is more reliable than an estimate.';};
  $('saveToCommand').onclick=()=>{if(!calculate(false))return;let state={};try{state=JSON.parse(localStorage.getItem('saveEarnPaulV31Plan'))||{};}catch(_){};Object.assign(state,{version:'3.1',propertyType:$('calcProperty').value,bedrooms:$('calcBedrooms').value,occupants:$('calcOccupants').value,heating:$('calcHeating').value,efficiency:$('calcEfficiency').value,daytime:$('calcDaytime').value,ev:$('calcEv').value,solar:$('calcSolar').value,energyMode:'actual',actualElectric:String(Math.round(last.e)),actualGas:String(Math.round(last.g)),meta:{...(state.meta||{}),updatedAt:new Date().toISOString()}});localStorage.setItem('saveEarnPaulV31Plan',JSON.stringify(state));window.showToast?.('Energy result saved to Command Centre');window.trackSafe?.('calculator_saved');};
  $('shareEnergy').onclick=async()=>{if(!calculate(false))return;const text=`Indicative annual energy result: ${fmt(last.e)} electricity${last.g?' and '+fmt(last.g)+' gas':''}.`;try{if(navigator.share)await navigator.share({title:'Energy result',text,url:location.href});else{await navigator.clipboard.writeText(text+' '+location.href);window.showToast?.('Result copied');}}catch(_){}};$('printEnergy').onclick=()=>{if(calculate(false))window.print()};actualFields();
})();
