
const $=id=>document.getElementById(id);let step=0;const steps=[...document.querySelectorAll('.calc-step')];
function showStep(n){step=Math.max(0,Math.min(steps.length-1,n));steps.forEach((s,i)=>s.classList.toggle('active',i===step));$('progressBar').style.width=((step+1)/steps.length*100)+'%';$('backBtn').style.visibility=step?'visible':'hidden';$('nextBtn').classList.toggle('hidden',step===steps.length-1);$('calculateBtn').classList.toggle('hidden',step!==steps.length-1)}
$('nextBtn').onclick=()=>showStep(step+1);$('backBtn').onclick=()=>showStep(step-1);
const bE={1:1700,2:2150,3:2500,4:3200,5:3900,6:4600},bG={1:6200,2:7800,3:9500,4:12200,5:15000,6:17800},pF={flat:.78,terrace:.92,semi:1,detached:1.18,bungalow:1.08},eF={efficient:.82,average:1,inefficient:1.22},oF={low:.94,mixed:1,high:1.1};
const fmt=n=>Math.round(n).toLocaleString('en-GB')+' kWh';
function estE(){const b=+$('bedrooms').value,p=+$('occupants').value;let v=bE[b]||5200;v+=Math.max(0,p-b)*320;v*=pF[$('propertyType').value]||1;v*=oF[$('daytime').value]||1;if($('ev').value==='yes')v+=2200;if($('solar').value==='yes')v*=.78;if($('heating').value==='electric')v+=6500;if($('heating').value==='heatpump')v+=2800;return Math.max(1000,v)}
function estG(){if($('heating').value!=='gas')return 0;const b=+$('bedrooms').value,p=+$('occupants').value;let v=bG[b]||20000;v+=Math.max(0,p-b)*400;v*=pF[$('propertyType').value]||1;v*=eF[$('efficiency').value]||1;return Math.max(3000,v)}
function calc(){const ae=+$('actualElectric').value,ag=+$('actualGas').value,use=$('usageMode').value==='actual',h=$('heating').value;let e,g,c,n;if(use&&(ae>0||ag>0)){e=ae>0?ae:estE();g=h==='gas'?(ag>0?ag:estG()):0;c=ae>0&&(h!=='gas'||ag>0)?'High':'Medium';n='Actual annual kWh has been used where supplied. Any missing figure has been estimated.'}else{e=estE();g=estG();c='Medium';n='Indicative estimate based on the home and household information supplied.'}$('electricResult').textContent=fmt(e);$('gasResult').textContent=g>0?fmt(g):'Not applicable';$('confidenceText').textContent='Confidence: '+c;$('confidenceDot').className='dot '+(c==='High'?'high':'');$('explanation').textContent=n;$('results').dataset.e=Math.round(e);$('results').dataset.g=Math.round(g);$('results').dataset.c=c;}
$('calculateBtn').onclick=calc;$('usageMode').onchange=()=>$('actualFields').classList.toggle('hidden',$('usageMode').value!=='actual');$('printBtn').onclick=()=>{calc();window.print()};$('whatsappBtn').onclick=()=>{calc();const e=+$('results').dataset.e,g=+$('results').dataset.g,c=$('results').dataset.c;const msg='Hi Paul, I used the Save & Earn calculator. My annual usage result is about '+e.toLocaleString('en-GB')+' kWh electricity and '+(g>0?g.toLocaleString('en-GB')+' kWh gas':'no gas estimate')+'. Confidence: '+c+'. Could we have a free chat?';window.open('https://wa.me/447925008477?text='+encodeURIComponent(msg),'_blank','noopener')};showStep(0);
